"""create all tables

Revision ID: 28f46d9f8b3c
Revises: 
Create Date: 2026-04-13 19:22:41.986915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f46d9f8b3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('discount_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('discount_code', sa.String(), nullable=False),
    sa.Column('discount_type', sa.Enum('FLAT', 'PERCENTAGE', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_level', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', name='discountstatus'), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('current_usage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('discount_id'),
    sa.UniqueConstraint('discount_code')
    )
    op.create_table('items',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_veg', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Enum('STARTER', 'MAIN_COURSE', 'DESSERT', 'BEVERAGE', 'SNACKS', 'SALAD', 'SOUP', 'ADD_ON', 'PIZZA', 'BURGER', 'SANDWICH', 'PASTA', name='itemcategory'), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('discount_code', sa.String(), nullable=True),
    sa.Column('order_status', sa.Enum('PENDING', 'FAILED', 'CANCELLED', 'CONFIRMED', 'PROCESSING', 'DELIVERED', 'SHIPPED', name='orderstatus'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('gateway_reference_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NET_BANKING', 'WALLET', name='paymentmethod'), nullable=True),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_in', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ROLE_USER', 'ROLE_ADMIN', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_total_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('refresh_tokens')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('items')
    op.drop_table('discounts')
    # ### end Alembic commands ###
